apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: quarkus-native
    app.kubernetes.io/component: quarkus-native
    app.kubernetes.io/instance: quarkus-native
  name: quarkus-native
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: quarkus-native:{{ .Values.microservices.config.quarkus.native.tag }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.microservices.config.quarkus.native.s2iimage }}
    type: Source
  successfulBuildsHistoryLimit: 5