apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-mandrel-quarkus-build
spec:
  params:
  - name: sub-project-name
    type: string   
  - name: workspace-subdir
    type: string               
  workspaces:
  - name: source
    description: The workspace where the source code will found
  steps:  
  - name: build
    image: quarkus/mandrel-21-rhel8:21.3
    command: ["/bin/bash", "-c"]   
    workingDir: /workspace/source/$(params.workspace-subdir)   
    args:
    - /workspace/source/$(params.workspace-subdir)/mvnw -f /workspace/source/$(params.workspace-subdir)/pom.xml -s /workspace/source/$(params.workspace-subdir)/custom-settings.xml clean package -Dnative -DskipTests=true -Dmaven.repo.local=/workspace/source/m2
    securityContext:
      runAsUser: 0    



